# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='internal',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x08internal\"\x1c\n\x08JSONTYPE\x12\x10\n\x08json_str\x18\x01 \x01(\tb\x06proto3')
)




_JSONTYPE = _descriptor.Descriptor(
  name='JSONTYPE',
  full_name='internal.JSONTYPE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_str', full_name='internal.JSONTYPE.json_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['JSONTYPE'] = _JSONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JSONTYPE = _reflection.GeneratedProtocolMessageType('JSONTYPE', (_message.Message,), dict(
  DESCRIPTOR = _JSONTYPE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:internal.JSONTYPE)
  ))
_sym_db.RegisterMessage(JSONTYPE)


# @@protoc_insertion_point(module_scope)
