# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpcdemo.common.internal.internal_pb2 as internal__pb2


class InternalServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Describe = channel.unary_unary(
        '/internal.InternalServer/Describe',
        request_serializer=internal__pb2.DescribeRequest.SerializeToString,
        response_deserializer=internal__pb2.ResourceReply.FromString,
        )
    self.Create = channel.unary_stream(
        '/internal.InternalServer/Create',
        request_serializer=internal__pb2.CreateRequest.SerializeToString,
        response_deserializer=internal__pb2.ResourceReply.FromString,
        )
    self.Update = channel.stream_stream(
        '/internal.InternalServer/Update',
        request_serializer=internal__pb2.UpdateRequest.SerializeToString,
        response_deserializer=internal__pb2.ResourceReply.FromString,
        )


class InternalServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Describe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InternalServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Describe': grpc.unary_unary_rpc_method_handler(
          servicer.Describe,
          request_deserializer=internal__pb2.DescribeRequest.FromString,
          response_serializer=internal__pb2.ResourceReply.SerializeToString,
      ),
      'Create': grpc.unary_stream_rpc_method_handler(
          servicer.Create,
          request_deserializer=internal__pb2.CreateRequest.FromString,
          response_serializer=internal__pb2.ResourceReply.SerializeToString,
      ),
      'Update': grpc.stream_stream_rpc_method_handler(
          servicer.Update,
          request_deserializer=internal__pb2.UpdateRequest.FromString,
          response_serializer=internal__pb2.ResourceReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'internal.InternalServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
